### ISSUE TITLE
CSS Request

### ISSUE THREAD

**Issue by austinstudio** [Quantas/shark-ng-table#108]
Your CSS file doesn't have prefixes for the styles that are used by the table.  This means that a style that says "th, td {" will affect all ths and tds in my entire application.  I have to override the padding that is being set by the shark CSS.

Can you please go through and prefix the CSS so that all styles for the shark table are exclusive to the shark table code?

**Comment by Quantas** [comment]
Absolutely. I will get started on that shortly. Thanks for the submission!
