### ISSUE TITLE
Columns disappear from chooser when column filtering is applied

### ISSUE THREAD

**Issue by joeymf** [Quantas/shark-ng-table#118]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
If you have column Chooser and field filtering enabled, Entering a value in a filter field will remove all unchecked items from the chooser list.

## Expected behavior
Columns in the chooser should always be available regardless of any other actions to the grid.

## Minimal reproduction of the problem with instructions
Using the starting point: https://plnkr.co/edit/Xus5zm?p=info
Uncheck the year from the column chooser
Enter 'WR' in the Model Filter field
Notice that Year has disappeared from the list of columns

## What is the motivation / use case for changing the behavior?
Users should be able to add/remove columns regardless of filters being applied.

## Environment

<pre><code>
shark-ng-table version: X.Y.Z
    "shark-ng-table": "^6.0.0",

Browser:
- [x ] Chrome (desktop) version 72.0.3626.121
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [X ] IE version 11.0.9600.17031
- [ ] Edge version XX

Others:

</code></pre>

**Comment by joeymf** [comment]
[reproducing columns disappearing.zip](https://github.com/Quantas/shark-ng-table/files/2964363/reproducing.columns.disappearing.zip)

**Comment by Quantas** [comment]
I've discovered the source of the issue. I will be working on the fix shortly and will hopefully have a new build some time this week. Thanks for the report @joeymf !
