### ISSUE TITLE
Examples of how to use linkTarget and linkKey.

### ISSUE THREAD

**Issue by JimWainner** [Quantas/shark-ng-table#121]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

Trying to use linkTarget and linkKey in a shark table to route to another page when the user selects a row.  Feature does not seem to work (for me!) and documentation or examples seem to not exist.

## Minimal reproduction of the problem with instructions

tms-user-maintenance-component.ts snippet
  tableColumns: SharkColumn[] = [
    { header: 'User ID', property: 'UserID', displayed: true },
    { header: 'First Name', property: 'APT_Emp_FirstName', displayed: true },
    { header: 'Last Name', property: 'APT_Emp_LastName', displayed: true },
    { header: 'Supervisor', property: 'SupervisorName', displayed: true },
    { header: 'Is Team Lead', property: 'Is_Team_Lead', displayed: true, pipe: BitToYesNoStringPipe },
    { header: 'Team Lead', property: 'TeamLeadID', displayed: true },
    { header: 'Enabled', property: 'Active', displayed: true, pipe: BitToYesNoStringPipe }
  ];

tms-user-maintenance-components.html snippet
  <div id="smallerTable" >
    <shark-table [data]="tmsUsers" [columns]="tableColumns" [columnOrdering]="false" [linkTarget]="[user/UserID]" [linkKey]="UserID" [columnFiltering]="true"
      [caption]="'All Users'" [hideCaption]="true" > ></shark-table>
  </div>

I can select a row, but nothing happens.

## Environment

<pre><code>
shark-ng-table version: X.Y.Z

Browser:
- [X] Chrome (desktop) version 74
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

**Comment by Quantas** [comment]
Thanks for the feedback! I will try to look into this before next week hopefully!

**Comment by alandsverk** [comment]
@JimWainner I've updated the sample site, please let me know what you think. https://www.quantasnet.com/shark-ng-table/#/row-link
