### ISSUE TITLE
Using ng-if to hide or show the Table displays: There are no colums selected

### ISSUE THREAD

**Issue by shaleen76** [Quantas/shark-ng-table#122]
## I'm submitting a...

<pre><code><div class="row" ng-if="true">
                                    <div class="col-md-12">
                                        <shark-table ng-if="" [data]="data" [localFilter]="true" [columns]="columns" [hideCaption]="true" [localPaging]="true" [localPagingSize]="10">
                                        </shark-table>
                                    </div>
                                </div>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[X ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

Code: 

## Current behavior

It is showing There are no columns selected.

## Expected behavior

 the expected behavior should not be showing the table or this verbiage.

## Environment

<pre><code>
<div class="row" ng-if="true">
                                    <div class="col-md-12">
                                        <shark-table ng-if="" [data]="data" [localFilter]="true" [columns]="columns" [hideCaption]="true" [localPaging]="true" [localPagingSize]="10">
                                        </shark-table>
                                    </div>
                                </div>
shark-ng-table version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:
<div class="row" ng-if="true">
                                    <div class="col-md-12">
                                        <shark-table ng-if="" [data]="data" [localFilter]="true" [columns]="columns" [hideCaption]="true" [localPaging]="true" [localPagingSize]="10">
                                        </shark-table>
                                    </div>
                                </div>
</code></pre>

**Comment by Quantas** [comment]
Hello! Thank you for the report! My apologies for not getting to this right away. I'll have to make a quick app that reproduces this issue to see if there is anything I can do. However, it may be that using ngIf to hide this component may not be supported. I will get back to you with confirmation though.

Thanks!

**Comment by Quantas** [comment]
@shaleen76 i have been unsuccessful in trying to reproduce this issue. I created a new (simple) example here: https://www.quantasnet.com/shark-ng-table/#/toggle-table 
For now, I'm going to close this issue. Please reply back or make a new ticket if you can provide an example of `ngIf` not working. Thanks!
