### ISSUE TITLE
feature request: selected row highlighted in table

### ISSUE THREAD

**Issue by mawky** [Quantas/shark-ng-table#123]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

We are currently using the shark-ng-table in a few of our applications. In a current application, we are using the table to show summary data, and when a row is clicked, we show detailed data in an editable form under the table. We would like to apply a style to the clicked row to identify that that is the currently selected row in the table.

## Expected behavior

Apply a style to the currently selected row in a table (essentially a highlight).

## What is the motivation / use case for changing the behavior?

Described above

## Environment

<pre><code>
shark-ng-table version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

**Comment by Quantas** [comment]
Sounds like a great idea! I’ll try to work on this very soon, thanks for the feedback!

**Comment by mawky** [comment]
@Quantas - Have you had a chance to look at this?

**Comment by Quantas** [comment]
Hello again @mawky , I'm really sorry that I did not get to this Issue again since my last comment. I was able to test a solution that works without needing a code change on my end. You just need to add some CSS after you import the shark-ng-table CSS file:

```
.shark-table .rowOpen {
  background-color: red;
}

.shark-table .child-row.rowOpen {
  background-color: white;
}

.shark-table .data-row.rowOpen > td {
  border-right: 1px solid red;
}

.shark-table .child-row.rowOpen > td {
  border-right: 1px solid white;
}
```

Please let me know if that will work for you.

**Comment by mawky** [comment]
Unfortunately I don't think that will work. We aren't using a child row. The first column acts as an "id" column with a link that loads the form below the shark-table. The form is not inline (in the table). If we had access to the rowOpen class without having the child row component, then I think we would be able to implement this. Also, one other thing to point out, we can only have one active row at a time due to the nature of the page. So when clicking on a row, we also need to un-highlight any previously selected rows.

We attempted to implement this using a service. This came close, but had a few bugs that we have been unable, to this point, to eliminate.
```
public highlightSelectedRow(renderer: Renderer2, el: ElementRef) {
        const sharkTableRow = renderer.parentNode(renderer.parentNode(renderer.parentNode(el.nativeElement)));
        const sharkTableBody = renderer.parentNode(sharkTableRow).querySelector('.previous-selected-row' + this.previousIndexValue);
        const currentIndex = sharkTableRow.rowIndex;
        const selectedLink = el.nativeElement.querySelector('a');

        /* Sets background focus class and aria-current value to row that is clicked on */
        renderer.addClass(sharkTableRow, 'active-row-focus');
        renderer.addClass(sharkTableRow, 'previous-selected-row' + currentIndex);
        renderer.addClass(selectedLink, 'selected-link' + currentIndex);
        renderer.setAttribute(el.nativeElement.querySelector('.selected-link' + currentIndex), 'aria-current', 'true');

        /* Removes background focus class and aria-selected attribute on previously selected row */
        while (sharkTableBody) {
          if (this.previousIndexValue !== currentIndex ) {
            renderer.removeAttribute(sharkTableBody.querySelector('.selected-link' + this.previousIndexValue), 'aria-current');
            renderer.removeClass(sharkTableBody, 'active-row-focus');
            renderer.removeClass(sharkTableBody, 'previous-selected-row' + this.previousIndexValue);
          }
          this.previousIndexValue = sharkTableRow.rowIndex;
          return false;
        }

        // Initialize the previous index value to use for testing the while loop
        if (!this.previousIndexValue) {
          this.previousIndexValue = currentIndex;
        }
    }
```

**Comment by mawky** [comment]
Actually, after spending some time this morning looking at/debugging this code, I may have found a solution that works for about 95% of the cases (and with much simpler code).

```
public highlightSelectedRow(renderer: Renderer2, el: ElementRef) {
        const sharkTableRow = renderer.parentNode(renderer.parentNode(renderer.parentNode(el.nativeElement)));
        const previousRow = renderer.parentNode(sharkTableRow).querySelector('.active-row-focus');
        const currentIndex = sharkTableRow.rowIndex;

        /* Removes background focus class and aria-selected attribute on previously selected row */
        while (previousRow && this.previousIndexValue !== currentIndex) {
          renderer.removeAttribute(previousRow, 'aria-current');
          renderer.removeClass(previousRow, 'active-row-focus');
          this.previousIndexValue = sharkTableRow.rowIndex;
        }

        /* Sets background focus class and aria-current value to row that is clicked on */
        renderer.addClass(sharkTableRow, 'active-row-focus');
        renderer.setAttribute(sharkTableRow, 'aria-current', 'true');
        return false;
    }
```

Unfortunately, this won't work in these cases:

1. When a user uses one of the pagination buttons to go to another page, and then navigates back, the row in the table will no longer be highlighted.

1. If we were to want a row selected on page load, we would not be able to apply the highlight.

**Comment by Quantas** [comment]
What feature are we looking to implement in the table? I’m trying to figure out how I can help :) Right now there is an EventEmmitter we could utilize to emit certain events.

**Comment by mawky** [comment]
I think the changes that we would like to make can be completed without any changes to the shark-table. If not, we will submit a new feature request with more information.
