### ISSUE TITLE
plnkr demo problems

### ISSUE THREAD

**Issue by adamlubek** [Quantas/shark-ng-table#81]
## I'm submitting a...

<pre><code>
[x] Bug report  
[x] Documentation issue or request
</code></pre>

## Current behavior
plnkr demo (https://embed.plnkr.co/Xus5zm/) does not work at all in IE11 and throws errors in chrome/edge when using basic table functionality (e.g. using filtering or expanding rows)

## Expected behavior
plnkr demo fully working without errors

## Minimal reproduction of the problem with instructions
see browser console when browsing https://embed.plnkr.co/Xus5zm/

Browser:
- [X] Chrome (desktop)
- [X] IE version 11
- [X] Edge

**Comment by Quantas** [comment]
Thanks for the bug report! I will look into this soon. :)

**Comment by Quantas** [comment]
I updated the plnkr, and tested in IE11, Edge, and Firefox, everything seems to be working from my end. Please verify and I will close this ticket.

**Comment by adamlubek** [comment]
thanks for prompt action. works without errors in chrome and edge now but IE11 doesn't work at all

![2018-02-27 09_51_50-](https://user-images.githubusercontent.com/8349742/36721840-f6221dda-1ba3-11e8-8ac3-e4ef341f6a37.png)

**Comment by Quantas** [comment]
I am a bit at a loss on IE11. My other sample site works there with no issues, and occasionally I can get plunker to work there with enough refreshes. I assure you that shark-ng-table works in IE11 with the proper polyfills loaded, so I am unsure if it's something with SystemJS, a missing polyfill, or something on plunker's end. This sample site does work in IE11 however: https://quantas.github.io/shark-ng-table-samples

**Comment by adamlubek** [comment]
yeah, that's strange. obviously up to you if you want to fix it but I think that leaving it as is might discourage potential users.

**Comment by alandsverk** [comment]
@adamlubek I've switched to Stackblitz for the runnable demo, I've tested it in all major browsers and everything seems to be good here. Please open up a new ticket if you still experience issues and I'll be happy to take a look.

**Comment by alandsverk** [comment]
Here is the link: https://stackblitz.com/edit/shark-ng-table-demo
